# Generated by Django 4.1.5 on 2023-01-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_dog_age_dog_breed_dog_description_picture_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='date_missing',
            field=models.DateField(default='2023-1-23'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='location',
            field=models.CharField(default='2023-1-23', max_length=50),
            preserve_default=False,
        ),
    ]
