# Generated by Django 4.1.5 on 2023-01-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_dog_date_missing_dog_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_created',
        ),
    ]
