# Generated by Django 4.1.5 on 2023-01-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_dog_date_missing_dog_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[('FOUND', 'Found'), ('LOST', 'lost')], default='FOUND', max_length=5),
        ),
    ]
