# Generated by Django 4.1.5 on 2023-01-25 02:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_merge_0004_dog_status_0006_alter_comment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[('NOT FOUND', 'Not Found'), ('FOUND', 'found')], default='NOT FOUND', max_length=10),
        ),
    ]
