<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.1.3 on 2023-01-25 18:18
=======
# Generated by Django 4.1.5 on 2023-01-25 03:12
>>>>>>> 925262d (add custom handler for permission exception)
=======
# Generated by Django 4.1.5 on 2023-01-25 15:22
>>>>>>> bbb1371 (add styling to index)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_key_name_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[('NOT FOUND', 'Not Found'), ('FOUND', 'Found')], default='NOT FOUND', max_length=10),
        ),
    ]
