# Generated by Django 4.1.3 on 2023-01-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_key_name_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[('NOT FOUND', 'Not Found'), ('FOUND', 'Found')], default='NOT FOUND', max_length=10),
        ),
    ]
