# Generated by Django 4.1.5 on 2023-01-25 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_dog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
