# Generated by Django 4.1.3 on 2023-01-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_city_location_state_alter_dog_date_missing'),
        ('main_app', '0011_dog_date_created'),
    ]

    operations = [
    ]
