# Generated by Django 4.1.3 on 2023-01-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20230126_1048'),
        ('main_app', '0012_merge_20230126_1049'),
    ]

    operations = [
    ]
