# Generated by Django 4.1.5 on 2023-01-27 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_merge_20230126_1131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
